### ISSUE TITLE
Обьясните код

### ISSUE THREAD

**Issue by TheZalesskiy** [makalex/java-rush#1]
Здраствуй! можете обьяснить что это за числа - "48, 65, 97, 10, 26" в level32.lesson06.task01.

**Comment by makalex** [comment]
http://4.bp.blogspot.com/-SznW6n_J1u4/UA7hlPYkJTI/AAAAAAAAFKE/fSeaEEd_UzQ/s640/ASCII+Codes+Char+Function.jpg

48 + random.nextInt(10) - числа 0-9
65 + random.nextInt(26) - буквы A-Z верхний регистр
65 + random.nextInt(26) - буквы a-z в нижнем регистре

**Comment by TheZalesskiy** [comment]
спасибо! понял
